// Get panels and buttons
const roleSelectPanel = document.getElementById('roleSelectPanel');
const teacherWrapper = document.getElementById('teacherWrapper');
const studentPanel = document.getElementById('studentPanel');

const btnGoTeacher = document.getElementById('btnGoTeacher');
const btnGoStudent = document.getElementById('btnGoStudent');
const backToRoleBtns = document.querySelectorAll('.backToRole');

const logregBox = document.querySelector(".logreg-box");

const BASE_URL = 'https://realaddress.com';//(not use yet)

// ==========================================
// 1. Role switching logic
// ==========================================
btnGoTeacher.addEventListener('click', () => {
  roleSelectPanel.classList.add('hidden');
  teacherWrapper.classList.remove('hidden');
});

btnGoStudent.addEventListener('click', () => {
  roleSelectPanel.classList.add('hidden');
  studentPanel.classList.remove('hidden');
});

// Go back to the role selection page when the "Back" button is clicked
backToRoleBtns.forEach(btn => {
  btn.addEventListener('click', () => {
    teacherWrapper.classList.add('hidden');
    studentPanel.classList.add('hidden');
    roleSelectPanel.classList.remove('hidden');

    // Reset the sliding state of the teacher login box to ensure it defaults to Login next time
    logregBox.classList.remove('active');
  });
});

// ==========================================
// 2. Teacher Login / Register sliding animation logic
// ==========================================
const loginLink = document.querySelector(".login-link");
const registerLink = document.querySelector(".register-link");

registerLink.addEventListener("click", (e) => {
  e.preventDefault();
  logregBox.classList.add("active");
});

loginLink.addEventListener("click", (e) => {
  e.preventDefault();
  logregBox.classList.remove("active");
});

// ==========================================
// 3. [NEW] Teacher real registration logic (Register)
// ==========================================
const registerForm = document.querySelector('.register');

registerForm.addEventListener('submit', async (e) => {
  e.preventDefault(); // Prevent default form submission and page refresh

  // Grab values from input fields (Order based on HTML: Email, Name, Password)
  const inputs = registerForm.querySelectorAll('input');
  const email = inputs[0].value;
  const username = inputs[1].value;
  const password = inputs[2].value;

  try {
    // Send POST request to backend (assuming Node.js runs on localhost:3000)(register change here)
    const response = await fetch('http://localhost:3000/api/auth/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email, full_name: username, password: password })
    });

    // If successful (status code 200 or 201)
    if (response.ok) {
      alert('Registration successful! Please log in.');
      logregBox.classList.remove("active"); // Smoothly slide back to the login interface
      registerForm.reset(); // Clear the completed form
    } else {
      // If backend returns an error (e.g., email already registered)
      const errorData = await response.json();
      alert('Registration failed: ' + (errorData.message || 'Unknown error'));
    }
  } catch (error) {
    console.error('Network Error:', error);
    alert('Cannot connect to the server. Is the Node.js backend running?');
  }
});

// ==========================================
// 4. [NEW] Teacher real login logic (Login)
// ==========================================
const loginForm = document.querySelector('.login');

loginForm.addEventListener('submit', async (e) => {
  e.preventDefault();

  const inputs = loginForm.querySelectorAll('input');
  const email = inputs[0].value;
  const password = inputs[1].value;

  try {//(teacher login URL change here)
    const response = await fetch('http://localhost:3000/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email, password: password })
    });

    if (response.ok) {
      const data = await response.json();
      alert('Login successful!');

      // ⚠️ CORE: Save the Token generated by the backend in the browser's local storage
      localStorage.setItem('gameDeckToken', data.token);

      // Redirect to the teacher's dashboard page (You need to create this file later)
      window.location.href = 'teacher-dashboard.html';
    } else {
      const errorData = await response.json();
      alert('Login failed: ' + (errorData.message || 'Wrong email or password'));
    }
  } catch (error) {
    console.error('Network Error:', error);
    alert('Cannot connect to the server. Is the Node.js backend running?');
  }
});

// ==========================================
// 5. [REAL] Student join room validation logic
// ==========================================
document.getElementById('studentForm').addEventListener('submit', async function (e) {
  e.preventDefault();

  // Get input values and force room code to uppercase (e.g., x7r2 to X7R2, fool-proofing)
  const roomCode = document.getElementById('roomCodeInput').value.toUpperCase();
  const nickname = document.getElementById('nicknameInput').value;

  try {
    // [Backend Integration Point 1: Modify this URL]
    // Once the Node.js backend is ready, replace the URL below with the real API address
    const response = await fetch('http://localhost:3000/api/session/join', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ join_code: roomCode, player_name: nickname })
    });

    if (response.ok) {
      // Room found successfully
      const data = await response.json();

      localStorage.setItem('gameDeckStudentId', data.player.session_player_id);
      localStorage.setItem('gameDeckSessionId', data.session.session_id); // 顺便把房间 ID 也存下来，Unity 可能会用

      alert("Welcome " + nickname + "! Room found. Loading Game...");


      // // [Backend Integration Point 2: Save backend credentials]
      // // To let Unity know which student entered, the backend usually returns a sessionToken. We need to save it.
      // localStorage.setItem('studentSessionToken', data.token); // Assuming backend returns { "token": "..." }

      // [Backend Integration Point 3: Modify redirect page]
      // Change this to the actual HTML file name where your Unity WebGL game is hosted.
      // Pass the room code in the URL parameters so Unity can read it.
      window.location.href = `unity-game.html?room=${roomCode}`;

    } else {
      // Handle errors (e.g., room not found, full, or game already started)
      const errorData = await response.json();
      alert("Error: " + (errorData.message || "Room code incorrect or game already started."));
    }
  } catch (error) {
    console.error('Network Error:', error);
    alert('Cannot connect to the server. Is the Node.js backend running?');
  }
});